-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    -   id: check-symlinks
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.1.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.0.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
